# Generated by Django 3.0.6 on 2020-05-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderPizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='platters',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='regular',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='sicilian',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Regular'},
        ),
    ]
