# Generated by Django 3.0.6 on 2020-05-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderPizza', '0002_auto_20200514_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name_plural': 'Pasta'},
        ),
        migrations.AlterModelOptions(
            name='platters',
            options={'verbose_name_plural': 'Platters'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name_plural': 'Salads'},
        ),
        migrations.AlterModelOptions(
            name='sicilian',
            options={'verbose_name_plural': 'Sicilian'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name_plural': 'Subs'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
